version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=dev-secret-key-change-in-production-123456789
      - DATABASE_URL=sqlite:///analisi_mu.db
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MAX_CONTENT_LENGTH=16777216
      - UPLOAD_FOLDER=uploads
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  instance:
    driver: local
  uploads:
    driver: local
  backups:
    driver: local